### ISSUE TITLE
WSJT document needs updating. 

### ISSUE THREAD

**Issue by scap1784** [g0orx/linhpsdr#81]
While I was able to get audio piped in for digital without issue following the directions. I haven't been able to get the cat to work. WSJTX doesn't have an option for network cat under OpenHPSDR PiHPSDR in the latest release it looks like.

![Screenshot from 2020-07-12 04-47-09](https://user-images.githubusercontent.com/1787703/87243379-3b75b980-c3fb-11ea-88a0-7b2fd1a8ea15.png)

**Comment by g0orx** [comment]
They have changed hamlib. I tried to get them to change it so there was both a serial interface and a TCP/IP interface shown.  In the latest version you need to put 127.0.0.1:19090.   This is not obvious in WSJT-X.  I have asked them to support hostname:port (i.e. localhost:19090) but not sure when that will be in a version of WSJT-X.   It really needs WSJT-X to change the UI interface so that it is more obvious that the device is not just a serial port.

**Comment by scap1784** [comment]
yup that was it. Thanks for the support it really is top notch!
